# docker-compose.yml
version: '3.11'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: flask-app
    ports:
        - 5000:8080
    env_file: .env
    environment:
        - COMET_API_KEY=${COMET_API_KEY}
    