# # docker-compose.yml
version: '3.11'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: flaskp-app
    ports:
        - 5000:8080
    environment:
        - COMET_API_KEY=${COMET_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: streamlit-app
    ports:
      - 8080:8080
    environment:
      - COMET_API_KEY=${COMET_API_KEY}


     
