# #   docker build -t <IMAGE TAG> -f Dockerfile.jupyter .
# # https://docs.docker.com/engine/reference/builder/#from
# # You shouldn't need to change this
FROM python:3.11

WORKDIR /code

ADD ./requirements.txt ./requirements.txt
ADD ./serving/app.py ./app.py

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8080

CMD ["gunicorn","--bind","0.0.0.0:8080","app:app"]

